import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>SRF MIS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Shamas MIS
        </h1>

        <p className={styles.description}>
          Sections
        </p>

        <div className={styles.grid}>
          <a href="#" className={styles.card}>
            <h2>Profiles &rarr;</h2>
            <p>View</p>
          </a>

          <a href="#" className={styles.card}>
            <h2>Attendance &rarr;</h2>
            <p>Record</p>
          </a>

          <a
            href="#"
            className={styles.card}
          >
            <h2>Visits &rarr;</h2>
            <p>Record</p>
          </a>

          <a
            href="#"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Life Skills &rarr;</h2>
            <p>
              Record
            </p>
          </a>
          <a
            href="#"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Registration &rarr;</h2>
            <p>
              Register
            </p>
          </a>
          <a
            href="#"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Education &rarr;</h2>
            <p>
              View records
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="#"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
